apiVersion: sqs.aws.upbound.io/v1beta1
kind: Queue
metadata:
  name: crossplane-queue
spec:
  forProvider:
    name: crossplane-queue
    region: us-east-1
  providerConfigRef:
    name: default

---
apiVersion: sqs.aws.upbound.io/v1beta1
kind: Queue
metadata:
  name: crossplane-queue-2
spec:
  forProvider:
    name: crossplane-queue
    region: us-east-1
  providerConfigRef:
    name: default
