apiVersion: sqs.aws.upbound.io/v1beta1
kind: Queue
metadata:
  name: crossplane-queue
spec:
  forProvider:
    name: crossplane-queue
    region: us-east-1
  providerConfigRef:
    name: default

---
apiVersion: ecr.aws.crossplane.io/v1beta1
kind: Repository
metadata:
  name: crossplane-ecr
  labels:
    region: us-east-1
spec:
  forProvider:
    region: us-east-1
    imageScanningConfiguration:
      scanOnPush: true
    imageTagMutability: IMMUTABLE
  providerConfigRef:
    name: example
