---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/argoproj/argo-helm.git
    targetRevision: argo-cd-7.5.0
    path: charts/argo-cd
    helm:
      values: |
        image:
          repository: quay.io/argoproj/argocd
  destination:
    name: in-cluster
    namespace: argocd
  syncPolicy:
    automated:
      prune: true    
    syncOptions:
    - CreateNamespace=true
