---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/crossplane/crossplane.git
    targetRevision: v1.16.1
    path: cluster/charts/crossplane
    helm:
      values: |
        image:
          repository: crossplane/crossplane
          tag: v1.16.1
  destination:
    name: in-cluster
    namespace: crossplane-system
  syncPolicy:
    automated:
      prune: true    
    syncOptions:
    - CreateNamespace=true
