---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-providers-aws
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  sources:
  - repoURL: https://github.com/dmroch4/argocd-crossplane.git
    targetRevision: main
    path: crossplane/providers
  destination:
    name: in-cluster
    namespace: crossplane-providers
  syncPolicy:
    automated:
      prune: true    
    syncOptions:
    - CreateNamespace=true
