---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-providers
  namespace: argocd
spec:
  project: default
  source:
  - repoURL: https://github.com/fabio-mrocha/argocd-crossplane.git
    targetRevision: main
    path: crossplane/providers
  destination:
    name: in-cluster
    namespace: crossplane-providers
  syncPolicy:
    automated:
      prune: true    
    syncOptions:
    - CreateNamespace=true
